# GitHub Actions workflow to lint the locale files.
name: "Lint"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  merge_group:

concurrency:
  group: "${{ github.workflow }}-${{ github.event.number || github.ref }}"
  cancel-in-progress: "${{ github.event.action != 'merge_group' }}"

permissions:
  contents: read

jobs:
  lint:
    name: "Lint"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
          submodules: true

      - name: "Setup Go stable"
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5
        with:
          go-version: "stable"
          cache: true
          check-latest: true

      - name: "Download dependencies"
        run: go mod download

      - name: "Verify dependencies"
        run: go mod verify

      - name: "Build"
        run: go build -v ./...

      - name: "Test"
        run: go test -race -v ./...

      - name: "Lint"
        run: |
          go build -trimpath ./cmd/lang-lint
          ./lang-lint
